### ISSUE TITLE
Do you have any plan in adding key mappings?

### ISSUE THREAD

**Issue by houqp** [nblock/vim-dokuwiki#3]
Add key mappings can save a lot of typing. Just like this one: http://www.vim.org/scripts/script.php?script_id=2374

BTW, I have created a mappings branch in my own fork :-)

**Comment by nblock** [comment]
I think this should be done with a snippet engine. Take a look at UltiSnips and my snippets here: https://github.com/nblock/nblock-snippets for reference.
